### ISSUE TITLE
The project name `.go` confuses the compiler a lot

### ISSUE THREAD

**Issue by jdevelop** [iotaledger/giota#29]
I recently discovered that if one forks this repo and adds a new package that uses some of the IOTA library internals - the compilation/tests are failing.

Some investigation / help from `#go-nuts@freenode` channel revealed that the suffix `.go` in the package name confuses the go tool in certain cases.

```
if len(args) > 0 && strings.HasSuffix(args[0], ".go") {
...
```

As a test, I renamed my local copy into `iota.lib.golang` - and the problem vanished.

Not sure whether it's a good idea to rename this package and what how many packages depend on this one, but just to keep this problem in mind.

**Comment by knarz** [comment]
I initially named it `giota` but was renamed by Dom, if I remember correctly, because they wanted the consistent naming.

You should also be able to import this as `github.com/iotaledger/giota`.

**Comment by jdevelop** [comment]
Yeah, `giota` might work and it's not generally a bug - just a hint to someone who either tries to fork/modify this project that if they have some weird problems with certain builds and/or IDE integration (like VSCode) - it could help to rename the project base folder.

**Comment by ramya-rao-a** [comment]
> You should also be able to import this as github.com/iotaledger/giota.

`import "github.com/iotaledger/giota"` results in "fails to find the package" error

**Comment by ramya-rao-a** [comment]
https://github.com/golang/go/issues/14923 is the upstream issue with golang that talks about not having import paths ending with `.go`

**Comment by knarz** [comment]
Just renamed it to giota again.
