### ISSUE TITLE
Switch to Googles Sha3

### ISSUE THREAD

**Issue by eaigner** [iotaledger/giota#30]
I've seen that the lib imports an external Sha3 implementation from `leb.io/hashland/keccakpg`. There is already a Sha3 implementation from Google in `golang.org/x/crypto/sha3`

The Google one has assembler optimized code for `amd64`. Is there a reason to use the 3rd party lib instead of the Google one?

Just curios.

**Comment by CWarner818** [comment]
This is very interesting. I would be interesting in seeing some benchmarks between the two.

**Comment by cwarner818** [comment]
I tried swapping it out (just edit the import in kerl.go) but it fails the tests. This is very interesting, as I wonder why the official google packages dont work but this seemingly random third-party package does.

**Comment by Pomyk** [comment]
sha3 is not the same as keccak. The difference is small though. From the /x/crypto/sha3 repo:

func New384() hash.Hash { return &state{rate: 104, outputLen: 48, dsbyte: 0x06} }

For keccak dsbyte should be 0x01, but there is no way to set it using that lib. You would have to fork it and modify.

**Comment by luca-moser** [comment]
switched to `golang.org/x/crypto/sha3` in `next` branch using a fork with dsbytes adjusted.
