### ISSUE TITLE
tests hang sometimes

### ISSUE THREAD

**Issue by deltaskelta** [iotaledger/giota#36]
I am seeing tests hanging sometimes in different spots, for instance right now my tests are stuck at `TestAPIGetTransactionsToApprove`.

I can see this has something to do with attaching to the tangle, or a maybe the node it is trying to attach to...I haven't seen enough faults to be able to narrow down exactly where it is failing. @knarz do you know specifically what is causing this?

**Comment by knarz** [comment]
These tests try connecting to a random node, which might or might not be reachable, iirc. They're not great, to say the least.

**Comment by deltaskelta** [comment]
hmm... do you know the underlying reason for this?

are the nodes jammed up with bandwith? are they improperly configured? or is there just not enough public nodes available? or is there some other reason they are failing to connect. 

I see most of these test functions give it 5 retries before failing. Would more retries help? How did you land on the number 5?

**Comment by knarz** [comment]
All of the above.

Ideally the unit tests wouldn't even connect to any nodes, imo. I did not write the tests but I would assume that five was just chosen arbitrarily.

**Comment by deltaskelta** [comment]
Yeah I had the same thought about the unit tests and not connecting, I'll see if there is anything I can do

**Comment by cwarner818** [comment]
What you need to do is write a custom http.Client that is mocked to just return a fixed JSON response for each test.

**Comment by phifty** [comment]
Hi everyone,
my strategy for this is usually to create a mock of the server node and than let the tests run against it. The tests would become network-independent and could be more isolated. It would be still possible to run them against a real node (via an environment switch).
I could work on this, but would like to know if this is appreciated since it could result in a bigger pull request?

**Comment by luca-moser** [comment]
Please keep track of this issue via https://github.com/iotaledger/giota/issues/81
