### ISSUE TITLE
Additional examples

### ISSUE THREAD

**Issue by Noki** [iotaledger/giota#42]
Hi!

It would be awesome to have some examples that show the following:

- [ ] Generate a new address and attach the address to the tangle
- [ ] Move balance from previously used and therefore insecure address to a newly generated address
- [ ] Send amount to recipient and move leftover balance to newly generated address
- [ ] Send to multiple recipients
- [ ] Promote a transaction

This would really help a lot.

Best regards
Tobias

**Comment by jjhesk** [comment]
thats good

**Comment by luca-moser** [comment]
We are in the process of creating usable documentation for developers on https://docs.iota.works/ (it is not finished yet but we have dedicated persons working on it). I've propagated your example requests to the corresponding persons.
