### ISSUE TITLE
Inconsistent API with JS lib

### ISSUE THREAD

**Issue by AaronVasquez** [iotaledger/giota#52]
Why does the `sendTrytes` func expect []Transaction instead of []Trytes
https://godoc.org/github.com/iotaledger/iota.lib.go#SendTrytes

Doesn't the JS lib expect an array of trytes? Why are they inconsistent?

**Comment by cwarner818** [comment]
Good point, I think a `SendTransactions` function would be better, so that the user doesn't have to convert between `Trytes` and `Transactions`.

**Comment by luca-moser** [comment]
`next`/v1.0.0 is/will be aligned with the iota.js library.
