### ISSUE TITLE
Dependency cannot be resolved

### ISSUE THREAD

**Issue by AaronVasquez** [iotaledger/giota#57]
I am using `dep ensure` to add giota as a dependency. I recently ran into this error:

```bash
Solving failure: No versions of github.com/iotaledger/giota met constraints:
	master: unable to deduce repository and source type for "leb.io/hashland": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://leb.io/hashland?go-get=1": Get http://leb.io/hashland?go-get=1: dial tcp 104.131.190.18:80: getsockopt: connection refused
```

**Comment by maeck70** [comment]
I think it is moved.
Doing some tests with a different source: github.com/hashland/keccakpg
file: kerl.go

**Comment by cwarner818** [comment]
It didn't move, really. Same package, they were just using their own domain to redirect there for some reason. No need, we'll just import directly.

**Comment by AaronVasquez** [comment]
@knarz Can you please take a look at  [#58](https://github.com/iotaledger/giota/pull/58)?

**Comment by knarz** [comment]
Merged, thank you
