### ISSUE TITLE
How to start a project

### ISSUE THREAD

**Issue by Rennbon** [iotaledger/giota#74]
I tried the demo on https://docs.iota.org/introduction/tutorials/first-transaction，
https://nodes.testnet.iota.org/ return 
{
  "error": "Invalid API Version",
  "duration": 0
}
I also tried golang,
giota/examples/getinputs/main won't work either

**Comment by luca-moser** [comment]
We are still in the progress of creating valuable documentation for developers under https://docs.iota.works/. In the meantime it might be better to use https://github.com/iotaledger/iota.js until the Go library is in a more mature state or you can dive into the `next` branch on this repo.
