### ISSUE TITLE
investigate if Go produces different bundles from the Java lib

### ISSUE THREAD

**Issue by knarz** [iotaledger/giota#8]
According to the exchange between [cfb and the MIT Researchers](https://gist.githubusercontent.com/Come-from-Beyond/a84ab8615aac13a4543c786f9e35b84a/raw/bb00cdf3625deba453d614f55c27f769b261df56/CFB's%2520letters%2520to%2520Neha%2520Narula's%2520team%2520during%2520their%2520analysis%2520of%2520Curl-P%2520hash%2520function) there might be an issue with bundles created by this library, as the foundation was not able to validate bundles generated by the MIT people who apparently used this library.

> [...]
> We can’t get your bundles to be validated successfully. It’s unclear if it’s a bug in the unfinished Go version or something else, we can’t check it right now because of the preparations to the snapshot.
> [...]

**Comment by Pomyk** [comment]
I was able to make a transfer using giotan with those kerl fixes.
